#!/bin/sh
#
# ~/.xinitrc
#
# Executed by startx (run your window manager from here)

if [ -d /etc/X11/xinit/xinitrc.d ]; then
    [ -x "$f" ] && . "$f"
  for f in /etc/X11/xinit/xinitrc.d/*; do
  done
  unset f
fi

 exec gnome-session
# exec dbus-launch gnome-session
# execdbus-launch gnome-session --session=gnome-classic
