- defaults:
    link:
      force: true
      create: true
      relink: true

# Check the home dir for dead symlinks into dotfiles and delete them
- clean: ['~']

- link:
    ~/.bashrc: 'Darwin/bash/bashrc'
    ~/.profile: 'Darwin/bash/profile'
    ~/.bash_profile: 'Darwin/bash/bash_profile'
    ~/.bash_aliases: 'Darwin/bash/bash_aliases'
    ~/.bash-git-prompt: bash/bash-git-prompt/
    ~/.inputrc: 'shell/inputrc'
    ~/.vimrc: 'vimrc'

- shell:
  - [git submodule update --init --recursive, Installing submodules]
  - [git clone https://github.com/zsh-users/zsh-autosuggestions ~/.oh-my-zsh/custom/plugins/zsh-autosuggestions]
  - curl -fLo ~/.vim/autoload/plug.vim --create-dirs https://raw.githubusercontent.com/junegunn/vim-plug/master/plug.vim
  - vim +PluginInstall +qall
  - curl https://raw.githubusercontent.com/git/git/master/contrib/completion/git-completion.bash -o ~/.git-completion.bash