#
# ~/.bash_aliases
#

# Colorization
# Use GRC for additionnal colorization
GRC=$(which grc)
if [ -n GRC ]; then
    alias colourify='$GRC -es --colour=auto'

    # CVS
    alias configure='colourify ./configure'
    alias diff='colourify diff'
    alias dig='colourify dig'
    alias gcc='colourify gcc'
    alias head='colourify head'
    alias ifconfig='colourify ifconfig'
    
    # IRC Log
    alias ld='colourify ld'
    
    # Log
    alias ls='colourify ls'
    alias make='colourify make'
    alias mount='colourify mount'
    
    # mtr
    alias netstat='colourify netstat'
    alias ping='colourify ping'
    #proftpd
    alias ps='colourify ps'
    alias tail='colourify tail'
    alias traceroute='colourify traceroute'
fi

	# ls
	PS1='[\u@\h \W]\$ '
	
	alias ls='ls --color=auto'
	alias ll='ls -ltrh'
	alias ..="cd .. && pwd"
	alias ...="cd ../.. && pwd"
	alias ....="cd ../../.. && pwd"
	alias .....="cd ../../../.. && pwd"
	alias home="cd $HOME"
	lso() { ls -la "$@" | awk '{k=0;for(i=0;i<=8;i++)k+=((substr($1,i+2,1)~/[rwx]/)*2^(8-i));if(k)printf(" %0o ",k);print}'; }
	
	# git
	alias gs='git status '
	alias ga='git add '
	alias gb='git branch '
	alias gc='git commit'
	alias gd='git diff'
	alias go='git checkout '
	alias gk='gitk --all&'
	alias gx='gitx --all'
	alias got='git '
	alias get='git '
    alias tig='git pull && tig'
	
	# Misc
	alias myip="wget http://ipinfo.io/ip -qO -"
	alias src='source ~/.bashrc'
	alias sudo='sudo'
	alias grep='grep --color=auto'
	alias logerrors='journalctl -p 0..3 -xn'
	alias reach='ping 8.8.8.8'
	
	# netstate
	alias watch='watch '
	alias nettotal="sudo netstat -np | grep -v ^unix"
	alias netall="sudo netstat -lantp | grep -i stab | awk -F/ '{print $2}' | sort | uniq"
	alias nettor="netstat -antcp | grep -i 9050"
	alias nethttp="sudo netstat -anp | grep :80 | grep ESTABLISHED | wc -l"
	alias nethttps="sudo netstat -anp | grep :443 | grep ESTABLISHED | wc -l"
	alias netdebug="while true; do netstat -a|grep WAIT|wc -l; sleep 5; done"
	alias netestablishedtcp="sudo netstat -an | grep -Ec '^tcp.+ESTABLISHED$'"
	alias listenports="netstat -anp --tcp --udp | grep LISTEN"
	alias openports="sudo netstat -ltun"

helmins() {
 kubectl -n kube-system create serviceaccount tiller
 kubectl create clusterrolebinding tiller --clusterrole cluster-admin --serviceaccount=kube-system:tiller
 helm init --service-account=tiller
}

helmdel() {
 kubectl -n kube-system delete deployment tiller-deploy
 kubectl delete clusterrolebinding tiller
 kubectl -n kube-system delete serviceaccount tiller

}
